### ISSUE TITLE
User can search their entries 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/code-journal#9]
## 💰 Motivation

Coders will want to search their entries to find specific ones they liked/need. 

## 📐 Plan

Allow users to search their entries with a provided search box that causes the entries list to only show matches. 

## ✅ Task List

- [x] Create a div to contain a new form for the search bar underneath "Entries" text & before entries.
- [x] Add input for text feature.
- [x] Add submit button (a search icon).
- [x] Ensure search bar and buttons look nice on both mobile-sized and desktop-sized screens.
- [x] Listen for 'submit' event on the search bar and: 
- [x] Create a loop that cycles through `li` to find ones whose content includes the search criteria: 
- [x] Ensure that proper results show.
- [x] If "no results" found, display text that says "no results found". 
- [x]  Show all the entry list items again.
- [x] Ensure that "clear results" works. 
- [x] Ensure if user clicks "entries" button, the search results are cleared & all results are shown. 
- [x] Clean up all unnecessary styling. 
- [x] Test the app some more in a private browsing tab. 
- [x] Fix all errors.
